[package]
name = "wasm-pack"
version = "0.1.0"
authors = ["Dudnik Pavel <ne.pridumal.nik@yandex.ru>"]
edition = "2021"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
actix-web = "*"
actix-files = "*"
