services:
  # База данных
  db:
    image: mysql
    restart: always
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      MYSQL_DATABASE: main_database
    ports:
      - "3306:3306"

  # Админка
  myadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ==PaSsWoRd==
      PMA_HOST: db
    ports:
      - "80:80"

  # Кэш
  redis:
    image: redis:alpine
    command: redis-server --requirepass ==PaSsWoRd==
    ports:
     - "6379:6379"